<?php
/**
 * @file
 * Epicodus Lab to use IMDB API to search movie titles.
 */

 /**
  * Implements hook_menu().
  */
function imdb_menu() {
    $items['search_imdb'] = array(
        'title' => 'Search Movies',
        'page callback' => 'drupal_get_form',
        'page arguments' => array('imdb_form'),
        'access callback' => TRUE,
        'type' => MENU_NORMAL_ITEM,
    );
    $items['imdb_sucess_page'] = array(
        'title' => 'IMDB Results',
        'page callback' => 'imdb_success',
        'access callback' => TRUE,
        'type' => MENU_CALLBACK,
    );

    return $items;
}

/**
 * Implements hook_form().
 */
function imdb_form() {
    $form['title_words'] = array(
        '#title' => 'Title',
        '#type' => 'textfield',
        '#description' => t('Enter movie title.'),
        '#required' => TRUE,
    );
    $form['submit'] = array(
        '#type' => 'submit',
        '#value' => 'Search IMDB for movie',
    );
    return $form;
}


/**
 * Implements hook_form().
 */
function imdb_page_form() {
    $form['submit'] = array(
        '#type' => 'submit',
        '#value' => 'Next Page of Movies',
    );
    return $form;
}


/**
 * Implements hook_form_submit().
 */
function imdb_form_submit($form, &$form_state) {
    $title_words = $form_state['values']['title_words'];
    $_SESSION['imdb_title_words'] = $title_words;
    $_SESSION['imdb_page'] = 1;
    $form_state['redirect'] = 'imdb_sucess_page';
    watchdog('imdb', 'imdb_form_submit');
}

/**
 * Implements hook_form_submit().
 */
function imdb_page_form_submit($form, &$form_state) {
    $_SESSION['imdb_page'] = $_SESSION['imdb_page'] + 1;
    $form_state['redirect'] = 'imdb_sucess_page';
    watchdog('imdb', 'imdb_page_form_submit');
}

function imdb_success() {
    $title_words = $_SESSION['imdb_title_words'];
    $imdb_page = (int) $_SESSION['imdb_page'];
    $title_query = array('s' => $title_words, 'page' => $imdb_page);
    $api_call = 'http://www.omdbapi.com/?' . http_build_query($title_query);
    $result_string = file_get_contents($api_call);
    $result_array = json_decode($result_string, TRUE);

    if ($result_array['Response'] === 'False') {
        return '<h1>No Results for your query!</h1>';
    }

    $output = '';

    for ($i=0; $i < count($result_array['Search']); $i++) {
       $movie_id = $result_array['Search'][$i]['imdbID'];
       $id_query = array('i' => $movie_id);
       $second_api_call = 'http://www.omdbapi.com/?' . http_build_query($id_query);
       $id_result_string = file_get_contents($second_api_call);
       $id_result_array = json_decode($id_result_string, TRUE);

       $output .= $output?'<hr>':'';
       $output .= '<h2>' . $result_array['Search'][$i]['Title'] . '</h2>';
       $output .= '<h3>' . $result_array['Search'][$i]['Year'] . '</h3>';
       $output .= '<h3>' . $result_array['Search'][$i]['Type'] . '</h3>';
       $output .= '<h3>' . $id_result_array['Director'] . '</h3>';
       $output .= '<h3>' . $id_result_array['Plot'] . '</h3>';
       $output .= '<h3>' . $id_result_array['Awards'] . '</h3>';
       $output .= '<h3>' . $id_result_array['imdbRating'] . '</h3>';
    }

    $button_output = drupal_get_form('imdb_page_form');
    $output .= drupal_render($button_output);
    // $output .= '<h3>Total Results Available: ' . $result_array['totalResults'] . '</h3>';
    // $output .= '<h3>API Call: ' . $api_call . '</h3>';
    // $output .= '<h3>Json</h3>';
    //
    // $output .= '<textarea>' . $result_string . '</textarea>';

    return $output;
}
